/**
 * Static topic manifest — title, level, keywords, and which batch to fetch.
 * Content (explanation, examples, exercise) is generated by Claude and cached.
 *
 * VERSION: bump this string whenever topics are added/changed to force cache invalidation.
 */
export const GRAMMAR_VERSION = 'v1'

const topics = [
  // ── A1 ──────────────────────────────────────────────────────────────────────
  {
    id: 'basic-sentence-structure',
    title: 'Basic sentence structure (SVO)',
    level: 'A1',
    keywords: ['sentence', 'subject', 'verb', 'object', 'word order', 'Satzstellung'],
    batch: 0,
  },
  {
    id: 'definite-articles',
    title: 'Definite articles (der / die / das)',
    level: 'A1',
    keywords: ['article', 'Artikel', 'der', 'die', 'das', 'gender', 'Genus'],
    batch: 0,
  },
  {
    id: 'present-tense',
    title: 'Present tense (Präsens)',
    level: 'A1',
    keywords: ['present', 'Präsens', 'conjugation', 'Konjugation', 'verb'],
    batch: 0,
  },
  {
    id: 'negation',
    title: 'Negation (nicht / kein)',
    level: 'A1',
    keywords: ['negation', 'nicht', 'kein', 'no', 'not'],
    batch: 0,
  },

  // ── A2 ──────────────────────────────────────────────────────────────────────
  {
    id: 'nominative-accusative',
    title: 'Nominative vs. Accusative case',
    level: 'A2',
    keywords: ['case', 'Kasus', 'nominative', 'Nominativ', 'accusative', 'Akkusativ'],
    batch: 0,
  },
  {
    id: 'modal-verbs',
    title: 'Modal verbs (können / müssen / wollen)',
    level: 'A2',
    keywords: ['modal', 'Modalverb', 'können', 'müssen', 'wollen', 'dürfen', 'sollen'],
    batch: 0,
  },
  {
    id: 'separable-verbs',
    title: 'Separable verbs (Trennbare Verben)',
    level: 'A2',
    keywords: ['separable', 'trennbar', 'prefix', 'Präfix', 'aufmachen', 'anrufen'],
    batch: 0,
  },
  {
    id: 'perfect-tense',
    title: 'Perfect tense (Perfekt)',
    level: 'A2',
    keywords: ['perfect', 'Perfekt', 'haben', 'sein', 'Partizip', 'past'],
    batch: 0,
  },

  // ── B1 ──────────────────────────────────────────────────────────────────────
  {
    id: 'v2-word-order',
    title: 'Verb-second word order (V2 rule)',
    level: 'B1',
    keywords: ['word order', 'Wortstellung', 'V2', 'verb second', 'inversion', 'Verb'],
    batch: 1,
  },
  {
    id: 'subordinate-clauses',
    title: 'Subordinate clauses (weil / dass / wenn)',
    level: 'B1',
    keywords: ['subordinate', 'Nebensatz', 'weil', 'dass', 'wenn', 'conjunction', 'Konjunktion'],
    batch: 1,
  },
  {
    id: 'dative-case',
    title: 'Dative case',
    level: 'B1',
    keywords: ['dative', 'Dativ', 'case', 'Kasus', 'mit', 'von', 'bei', 'nach'],
    batch: 1,
  },
  {
    id: 'two-way-prepositions',
    title: 'Two-way prepositions (Wechselpräpositionen)',
    level: 'B1',
    keywords: ['preposition', 'Präposition', 'in', 'an', 'auf', 'über', 'unter', 'vor', 'hinter', 'neben', 'zwischen', 'accusative', 'dative'],
    batch: 1,
  },
  {
    id: 'reflexive-verbs',
    title: 'Reflexive verbs (Reflexive Verben)',
    level: 'B1',
    keywords: ['reflexive', 'sich', 'reflexiv', 'mich', 'dich', 'sich', 'uns', 'euch'],
    batch: 1,
  },

  // ── B2 ──────────────────────────────────────────────────────────────────────
  {
    id: 'passive-voice',
    title: 'Passive voice (Passiv)',
    level: 'B2',
    keywords: ['passive', 'Passiv', 'werden', 'von', 'agent'],
    batch: 1,
  },
  {
    id: 'konjunktiv-ii',
    title: 'Konjunktiv II (würden / wäre / hätte)',
    level: 'B2',
    keywords: ['Konjunktiv', 'subjunctive', 'würden', 'wäre', 'hätte', 'conditional', 'hypothetical'],
    batch: 1,
  },
  {
    id: 'relative-clauses',
    title: 'Relative clauses (Relativsätze)',
    level: 'B2',
    keywords: ['relative', 'Relativsatz', 'der', 'die', 'das', 'welcher', 'relative pronoun'],
    batch: 1,
  },
]

export default topics
